<?php
/**
 * @file
 * DrupalOOP example code.
 */

/**
 * Implements hook_init().
 */
function drupaloop_example_init() {
  $module = DrupaloopExampleModule::load();

  drupal_set_message($module->varGet('demo_message'), 'status', FALSE);
}

/**
 * Implements hook_filter_info().
 */
function drupaloop_example_filter_info() {
  $filters = array();

  // Register the Drupal Capitalizer filter.
  DrupaloopExampleDrupalCapFilter::load()->addFilter($filters);

  return $filters;
}

/**
 * Implements hook_block_info().
 */
function drupaloop_example_block_info() {
  $blocks = array();

  // Register the welcome block.
  DrupaloopExampleWelcomeBlock::load()->addBlock($blocks);

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function drupaloop_example_block_view($delta = '') {
  // This is all we need if all our blocks are objects.
  if ($block = DrupaloopExampleModule::load()->loadBlock($delta)) {
    return $block->view();
  }
}

/**
 * Implements hook_block_configure().
 */
function drupaloop_example_block_configure($delta = '') {
  if ($block = DrupaloopExampleModule::load()->loadBlock($delta)) {
    return $block->form();
  }
}

/**
 * Implements hook_block_save().
 */
function drupaloop_example_block_save($delta = '', $edit = array()) {
  if ($block =DrupaloopExampleModule::load()->loadBlock($delta)) {
    $block->save($edit);
  }
}
